server:
  port: 8761
spring:
  application:
    name: eshop-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false